config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'games#index'
  resources :games # NHO: any merit to nested resource `games` under `users`? Or all games available to all users
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  # NHO: would recommend adding validations on games to help prevent bad user created data
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :games # NHO: since a user has many games,
  # one feature idea would be to have a "my games" page showing all of a user's associated games

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @featured_games = Game.where(featured: true)
    # NHO: Like this idea, who decides what games are featured? Could also include an index of all games / filter
  end

  # new
  def new
    @game = Game.new
  end

  # create
  def create
    @game = Game.create!(game_params)

    redirect_to root_path
  end

  #show
  def show
    @game = Game.find(params[:id])
  end

  # edit
  def edit
    @game = Game.find(params[:id])
  end


  # update
  def update
    @game = Game.find(params[:id])
    @game.update(game_params)
    redirect_to game_path(@game)
  end

  # destroy
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    redirect_to games_path
  end



  private
  def game_params
    params.require(:game).permit(:name, :img_url, :release_date, :price, :featured, :photo_url, :tags)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
# NHO: reminder to remove unused code
module CategoryHelper
end

app/helpers/controllers_helper.rb
# NHO: reminder to remove unused code
module ControllersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<!-- adds forms for each attr  -->
<%= form_for(@game) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :price %>
    <!-- makes sure that decimals are accepted in number field -->
    <%= f.number_field :price, :step => 'any' %>
    <br>
    <%= f.label :release_date %>
    <%= f.date_field :release_date  %>
    <br>
    <%= f.label :featured %>
    <%= f.check_box  :featured,     default: false %>
    <br>
    <%= f.label :photo_url %>
    <%= f.url_field   :photo_url %>
    <br>
    <%= f.submit %>

<% end %>

app/views/games/edit.html.erb
<div class="devise_forms">
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> 
<%= link_to 'Back', games_path %>
</div>

app/views/games/index.html.erb
<% if current_user %>
  <div id="myCarousel" class="carousel slide myCarousel" data-ride="carousel">

    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <% @featured_games.each do |game| %>
        <li data-target="#myCarousel" data-slide-to="<%=game.id%>"></li>
      <% end %>
    </ol>

    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <div class="first_picture">
          <%=link_to image_tag("http://s10.postimg.org/b6igfrtux/Drawing_12.png"), new_game_path%>
        </div>
        <!-- NHO: reminder to remove commented out code -->
        <!-- <img class="first_picture"src="http://s14.postimg.org/rvn7kdcdt/Drawing_11.png" alt="gamr logo"/> -->

      </div>
      <% @featured_games.each do |game| %>
        <div class="item">
          <%=link_to image_tag(game.photo_url), game_path(game)%>
        </div>
      <% end %>
    </div>

    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <h2>Games</h2>
  
  <div class="container-fluid all_games">
    <!-- NHO: This works, but we want to have our data queries in the controller  -->
    <% Game.all.each do |game| %>
    <div class="row">
      <div class="col-sm-12 sidebar centered">
        <%= link_to game.name, game_path(game.id) %>
      </div>
    </div>
    <% end %>
  </div>

  </div> <!-- NHO: is this a stray closing div tag? -->

<% else %>
  <div class="devise_forms">
    <%= "you must be signed in to view content!" %>
  </div>
<% end %>

<script type="text/javascript">
  $("#myCarousel").carousel();

  $(".item").click(function () {
    $("#myCarousel").carousel(1);
  });

  $(".left").click(function () {
    $("#myCarousel").carousel("prev");
  });
</script>

app/views/games/new.html.erb
<div class="devise_forms">
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>
</div>

app/views/games/show.html.erb
<!-- shows current selected game  -->
<div class="show_page">
  <h1> <%= @game.name %> </h1>
  <img src="<%=@game.photo_url%>" alt="<%=@game.name%>"/>
</div>
<!-- makes a nav wth nav-pills bootstrap styling  -->
<ul class="nav nav-pills">
  <li>  <%= link_to 'Edit', edit_game_path(@game)%></li>
  <li>  <%= link_to 'Back', games_path %></li>
  <li>  <%= link_to 'Delete', game_path(@game), method: :delete %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Gamr</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
</head>

<body>


  <div class="registration">
    <% if !current_user %>
    <%= link_to "Sign Up", new_user_registration_path %>
    <%= " " %> <!-- NHO: is this space necessary? -->
    <%= link_to "Sign In", new_user_session_path %>
    <%else%>
    <%= link_to "Log Out of #{current_user.email}", destroy_user_session_path, method: :delete %>
    <%end%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>

  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <div class="mainLogo">
        <%=link_to image_tag("http://s11.postimg.org/u7k39xs0z/Drawing_10.png"), root_path%>
      </div>
    </div>
  </div>



  <%= yield %>


</body>
</html>